// src/views/MinistryWithTasks.js
window.Views = window.Views || {};

window.Views.MinistryWithTasks = ({ title, col, filterMinistry, members, tasks, events, addData, deleteData, updateData }) => {
    const { useState, useMemo } = React;
    const { Card, Button, Badge, Modal, Input, Select, MonthNav, formatDate, formatTime, Icon, SmartSelect } = window.Utils;

    const [activeTab, setActiveTab] = useState('events');
    const [currentDate, setCurrentDate] = useState(new Date());
    const [isAddingEvent, setIsAddingEvent] = useState(false);
    const [evtForm, setEvtForm] = useState({ date: '', time: '', title: '', type: 'Reunión', assignments: {}, details: {} });
    const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);
    const [editingTask, setEditingTask] = useState(null);
    const [taskForm, setTaskForm] = useState({ description: '', assignedTo: '', dueDate: '', status: 'Pendiente', checklist: [], notes: '' });
    const [newCheckItem, setNewCheckItem] = useState('');

    const memberOptions = useMemo(() => members.filter(m => m.ministry === filterMinistry || m.role === 'Líder' || m.role === 'Pastor').map(m => ({ value: m.name, label: m.name })), [members, filterMinistry]);
    const monthlyEvents = useMemo(() => events.filter(e => e.date && e.date.startsWith(currentDate.toISOString().slice(0, 7))).sort((a,b) => new Date(a.date) - new Date(b.date)), [events, currentDate]);
    const ministryTasks = tasks.filter(t => t.ministry === col).sort((a,b) => new Date(a.dueDate) - new Date(b.dueDate));

    const handleAssignment = (role, name) => setEvtForm(p => ({ ...p, assignments: { ...p.assignments, [role]: name } }));
    const handleDetail = (field, value) => setEvtForm(p => ({ ...p, details: { ...p.details, [field]: value } }));
    const saveEvent = () => { if(!evtForm.date) return alert("Faltan datos"); addData(col, evtForm); setIsAddingEvent(false); setEvtForm({ date: '', time: '', title: '', type: 'Reunión', assignments: {}, details: {} }); };
    
    const openTaskModal = (task = null) => { setEditingTask(task); setTaskForm(task || { description: '', assignedTo: '', dueDate: '', status: 'Pendiente', checklist: [], notes: '' }); setIsTaskModalOpen(true); };
    const addCheckItem = () => { if(!newCheckItem.trim()) return; setTaskForm(p => ({ ...p, checklist: [...(p.checklist || []), { id: Date.now(), text: newCheckItem, done: false }] })); setNewCheckItem(''); };
    const toggleCheckItem = (id) => setTaskForm(p => ({ ...p, checklist: p.checklist.map(i => i.id === id ? { ...i, done: !i.done } : i) }));
    const saveTask = () => { if(!taskForm.description) return alert("Descripción requerida"); const d = { ...taskForm, ministry: col }; editingTask ? updateData('tasks', editingTask.id, d) : addData('tasks', d); setIsTaskModalOpen(false); };

    const renderFields = () => {
        if (col === 'ebd') return (<div className="space-y-3 bg-slate-50 p-4 rounded-xl border border-slate-100"><h4 className="font-bold text-sm text-slate-700">Detalles Clase</h4><Input label="Tema" value={evtForm.details?.topic} onChange={e=>handleDetail('topic', e.target.value)} /><div className="grid grid-cols-2 gap-4"><SmartSelect label="Maestro" options={memberOptions} value={evtForm.assignments?.Maestro} onChange={v=>handleAssignment('Maestro', v)} /><SmartSelect label="Ayudante" options={memberOptions} value={evtForm.assignments?.Ayudante} onChange={v=>handleAssignment('Ayudante', v)} /></div></div>);
        if (col === 'youth') return (<div className="space-y-3 bg-slate-50 p-4 rounded-xl border border-slate-100"><h4 className="font-bold text-sm text-slate-700">Reunión</h4><Input label="Tema" value={evtForm.details?.topic} onChange={e=>handleDetail('topic', e.target.value)} /><Input label="Juego" value={evtForm.details?.game} onChange={e=>handleDetail('game', e.target.value)} /></div>);
        if (col === 'servers') return (<div className="space-y-3 bg-slate-50 p-4 rounded-xl border border-slate-100"><h4 className="font-bold text-sm text-slate-700">Orden</h4><Input label="Predicador" value={evtForm.details?.preacher} onChange={e=>handleDetail('preacher', e.target.value)} /><div className="grid grid-cols-2 gap-3">{['Recepción','Baños','Altar'].map(r=>(<SmartSelect key={r} label={r} options={memberOptions} value={evtForm.assignments?.[r]} onChange={v=>handleAssignment(r, v)} />))}</div></div>);
    };

    return (
        <div className="space-y-6 fade-in">
            <div className="flex justify-between items-center"><h2 className="text-2xl font-bold">{title}</h2><div className="flex bg-white p-1 rounded-xl shadow-sm"><button onClick={()=>setActiveTab('events')} className={`px-4 py-2 rounded-lg text-sm font-bold ${activeTab==='events'?'bg-brand-50 text-brand-600':'text-slate-500'}`}>Calendario</button><button onClick={()=>setActiveTab('tasks')} className={`px-4 py-2 rounded-lg text-sm font-bold ${activeTab==='tasks'?'bg-brand-50 text-brand-600':'text-slate-500'}`}>Tareas</button></div></div>
            {activeTab === 'events' && (<><MonthNav currentDate={currentDate} onMonthChange={setCurrentDate} /><div className="flex justify-end mb-4"><Button icon="Plus" onClick={()=>{setEvtForm({...evtForm, date: new Date().toISOString().split('T')[0]}); setIsAddingEvent(true);}}>Nuevo</Button></div><div className="space-y-4">{monthlyEvents.map(e => (<Card key={e.id} className="group relative hover:border-brand-300"><div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={()=>deleteData(col, e.id)} className="p-2 bg-red-50 text-red-600 rounded-lg"><Icon name="Trash" size={16}/></button></div><div className="flex gap-4"><div className="flex flex-col items-center justify-center bg-brand-50 text-brand-700 rounded-xl min-w-[70px] px-2 py-3 h-fit border border-brand-100"><span className="text-xs font-bold uppercase">{new Date(e.date).toLocaleDateString('es-AR',{weekday:'short'})}</span><span className="text-2xl font-black">{new Date(e.date).getDate()}</span></div><div className="flex-1"><div className="flex items-center gap-2 mb-1"><Badge type="brand">{e.type}</Badge><span className="text-xs font-bold text-slate-400">{e.time} hs</span></div><h3 className="font-bold text-lg">{e.title}</h3>{e.details?.preacher && <p className="text-sm text-slate-600">🎤 {e.details.preacher}</p>}{e.assignments && <div className="mt-3 flex flex-wrap gap-2">{Object.entries(e.assignments).map(([r,p])=><span key={r} className="text-xs bg-slate-50 border px-2 py-1 rounded"><strong>{r}:</strong> {p}</span>)}</div>}</div></div></Card>))}</div><Modal isOpen={isAddingEvent} onClose={()=>setIsAddingEvent(false)} title="Nuevo Evento"><div className="space-y-4 max-h-[75vh] overflow-y-auto pr-1"><div className="grid grid-cols-2 gap-4"><Input type="date" label="Fecha" value={evtForm.date} onChange={e=>setEvtForm({...evtForm, date:e.target.value})} /><Input type="time" label="Hora" value={evtForm.time} onChange={e=>setEvtForm({...evtForm, time:e.target.value})} /></div><Input label="Título" value={evtForm.title} onChange={e=>setEvtForm({...evtForm, title:e.target.value})} />{renderFields()}<Button className="w-full" onClick={saveEvent}>Guardar</Button></div></Modal></>)}
            {activeTab === 'tasks' && (<><div className="flex justify-end mb-4"><Button icon="Plus" onClick={()=>openTaskModal()}>Nueva Tarea</Button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{ministryTasks.map(t => (<div key={t.id} onClick={()=>openTaskModal(t)} className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm hover:shadow-md cursor-pointer"><div className="flex justify-between items-start mb-2"><Badge type={t.status === 'Completada' ? 'success' : 'warning'}>{t.status}</Badge>{t.dueDate && <span className="text-[10px] font-bold text-slate-400 bg-slate-50 px-2 py-1 rounded">{formatDate(t.dueDate)}</span>}</div><h4 className="font-bold text-slate-800 mb-1">{t.description}</h4><p className="text-xs text-slate-500">Resp: {t.assignedTo}</p></div>))}</div><Modal isOpen={isTaskModalOpen} onClose={()=>setIsTaskModalOpen(false)} title="Tarea"><div className="space-y-5 max-h-[75vh] overflow-y-auto"><Input label="Título" value={taskForm.description} onChange={e=>setTaskForm({...taskForm, description:e.target.value})} /><SmartSelect label="Responsable" options={memberOptions} value={taskForm.assignedTo} onChange={v=>setTaskForm({...taskForm, assignedTo:v})} /><Input type="date" label="Vence" value={taskForm.dueDate} onChange={e=>setTaskForm({...taskForm, dueDate:e.target.value})} /><div className="bg-slate-50 p-4 rounded-xl border border-slate-100"><label className="block text-xs font-bold text-slate-900 uppercase mb-2">Checklist</label><div className="flex gap-2 mb-3"><input className="w-full bg-white border border-slate-300 text-slate-900 font-medium rounded-xl px-4 py-2 text-sm outline-none" placeholder="Item..." value={newCheckItem} onChange={e=>setNewCheckItem(e.target.value)} /><button onClick={addCheckItem} className="bg-slate-200 p-2 rounded-lg"><Icon name="Plus"/></button></div><div className="space-y-2">{(taskForm.checklist||[]).map(i=>(<div key={i.id} className="flex items-center gap-3 bg-white p-2 rounded-lg border"><input type="checkbox" checked={i.done} onChange={()=>toggleCheckItem(i.id)} /><span className={i.done?'line-through text-slate-400':''}>{i.text}</span></div>))}</div></div><Button className="w-full" onClick={saveTask}>Guardar</Button>{editingTask && <button onClick={()=>{deleteData('tasks', editingTask.id); setIsTaskModalOpen(false)}} className="text-red-500 text-xs w-full text-center mt-2">Eliminar</button>}</div></Modal></>)}
        </div>
    );
};
